server:
  port: 3000

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
datasource:
  url: jdbc:mariadb://localhost:3306/masterdb?useSSL=false
  slave-list:
    - slavename: slave_1
      slaveurl: jdbc:mariadb://localhost:3306/slavedb?useSSL=false
  username: root
  password: Yesung2!
logging:
  level:
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    org.hibernate.SQL: DEBUG